server:
  port: 8000

spring:
  application:
    name: gateway

  #Config gateway
  cloud:
    gateway:
      routes:
#        - id: auth-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/auth/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
#          issuer-uri: https://securetoken.google.com/${FIREBASE_PROJECT_ID}

#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true

#SpringDoc config
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    urls:
#      - name: Auth Service
#        url: auth/v3/api-docs
      - name: User Service
        url: users/v3/api-docs
      - name: Product Service
        url: products/v3/api-docs
      - name: Order Service
        url: orders/v3/api-docs

#Eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost